#!/bin/bash

# 1. Crear una imagen con un servidor web Apache y el mismo contenido que en la carpeta content (fijate en el Dockerfile con el que cree simple-nginx)

#Modifico la copia del Dockerfile con las especificaciones del ejercicio:

#Imagen que voy a utilizar como base
FROM httpd:alpine
#Etiquetado
LABEL maintainer="LuisDemetrioFP"
LABEL project="Ejercicio01DockerSesion02"

#Como metadato, indicamos que el contenedor utiliza el puerto 80
EXPOSE 80

#Modificaciones sobre la imagen que he utilizado como base, en este caso alpine
COPY content/ /usr/local/apache2/htdocs/%                                       

#Y ejecuto con el comando build y con el nombre de contenedor simple-apache.

docker build . -t simple-apache

exit
